"and" @keyword
"any" @keyword
"as" @keyword
"asc" @keyword
"any" @keyword
"avg" @keyword
"boolean" @keyword
"by" @keyword
"class" @keyword
"newtype" @keyword
"count" @keyword
"date" @keyword
"desc" @keyword
"else" @keyword
"exists" @keyword
"extends" @keyword
"false" @keyword
"float" @keyword
"forall" @keyword
"forex" @keyword
"from" @keyword
"if" @keyword
"implies" @keyword
"import" @keyword
"in" @keyword
"instanceof" @keyword
"int" @keyword
"max" @keyword
"min" @keyword
"module" @keyword
"not" @keyword
"none" @keyword
"or" @keyword
"order" @keyword
"predicate" @keyword
"rank" @keyword
"result" @keyword
"select" @keyword
"strictcount" @keyword
"strictsum" @keyword
"strictconcat" @keyword
"concat" @keyword
"string" @keyword
"sum" @keyword
"super" @keyword
"then" @keyword
"this" @keyword
"true" @keyword
"where" @keyword



(typeExpr (upperId) @type)
